  committees = {
    KOM_11_: {
      color: "black",
      de: "Staatspolitische Kommission NR",
      fr: "Staatspolitische Kommission NR",
      it: "Staatspolitische Kommission NR",
      rm: "Staatspolitische Kommission NR",
      en: "Staatspolitische Kommission NR",
    },
    KOM_31_: {
      color: "black",
      de: "Delegation beim Europarat",
      fr: "Delegation beim Europarat",
      it: "Delegation beim Europarat",
      rm: "Delegation beim Europarat",
      en: "Delegation beim Europarat",
    },
    KOM_6_: {
      color: "black",
      de: "Kommission für soziale Sicherheit und Gesundheit NR",
      fr: "Kommission für soziale Sicherheit und Gesundheit NR",
      it: "Kommission für soziale Sicherheit und Gesundheit NR",
      rm: "Kommission für soziale Sicherheit und Gesundheit NR",
      en: "Kommission für soziale Sicherheit und Gesundheit NR",
    },
    KOM_7_: {
      color: "black",
      de: "Kommission für Umwelt, Raumplanung und Energie NR",
      fr: "Kommission für Umwelt, Raumplanung und Energie NR",
      it: "Kommission für Umwelt, Raumplanung und Energie NR",
      rm: "Kommission für Umwelt, Raumplanung und Energie NR",
      en: "Kommission für Umwelt, Raumplanung und Energie NR",
    },
    KOM_707_: {
      color: "black",
      de: "Delegation für die Beziehungen zum Deutschen Bundestag",
      fr: "Delegation für die Beziehungen zum Deutschen Bundestag",
      it: "Delegation für die Beziehungen zum Deutschen Bundestag",
      rm: "Delegation für die Beziehungen zum Deutschen Bundestag",
      en: "Delegation für die Beziehungen zum Deutschen Bundestag",
    },
    KOM_940_: {
      color: "black",
      de: "Immunitätskommission NR",
      fr: "Immunitätskommission NR",
      it: "Immunitätskommission NR",
      rm: "Immunitätskommission NR",
      en: "Immunitätskommission NR",
    },
    KOM_2_: {
      color: "black",
      de: "Finanzkommission NR",
      fr: "Finanzkommission NR",
      it: "Finanzkommission NR",
      rm: "Finanzkommission NR",
      en: "Finanzkommission NR",
    },
    KOM_3_: {
      color: "black",
      de: "Geschäftsprüfungskommission NR",
      fr: "Geschäftsprüfungskommission NR",
      it: "Geschäftsprüfungskommission NR",
      rm: "Geschäftsprüfungskommission NR",
      en: "Geschäftsprüfungskommission NR",
    },
    KOM_76_: {
      color: "black",
      de: "Geschäftsprüfungsdelegation",
      fr: "Geschäftsprüfungsdelegation",
      it: "Geschäftsprüfungsdelegation",
      rm: "Geschäftsprüfungsdelegation",
      en: "Geschäftsprüfungsdelegation",
    },
    KOM_971_: {
      color: "black",
      de: "Koordinationsgruppe der Geschäftsprüfungskommissionen",
      fr: "Koordinationsgruppe der Geschäftsprüfungskommissionen",
      it: "Koordinationsgruppe der Geschäftsprüfungskommissionen",
      rm: "Koordinationsgruppe der Geschäftsprüfungskommissionen",
      en: "Koordinationsgruppe der Geschäftsprüfungskommissionen",
    },
    KOM_9_: {
      color: "black",
      de: "Kommission für Verkehr und Fernmeldewesen NR",
      fr: "Kommission für Verkehr und Fernmeldewesen NR",
      it: "Kommission für Verkehr und Fernmeldewesen NR",
      rm: "Kommission für Verkehr und Fernmeldewesen NR",
      en: "Kommission für Verkehr und Fernmeldewesen NR",
    },
    KOM_1_: {
      color: "black",
      de: "Büro NR",
      fr: "Büro NR",
      it: "Büro NR",
      rm: "Büro NR",
      en: "Büro NR",
    },
    KOM_8_: {
      color: "black",
      de: "Sicherheitspolitische Kommission NR",
      fr: "Sicherheitspolitische Kommission NR",
      it: "Sicherheitspolitische Kommission NR",
      rm: "Sicherheitspolitische Kommission NR",
      en: "Sicherheitspolitische Kommission NR",
    },
    KOM_5_: {
      color: "black",
      de: "Kommission für Wissenschaft, Bildung und Kultur NR",
      fr: "Kommission für Wissenschaft, Bildung und Kultur NR",
      it: "Kommission für Wissenschaft, Bildung und Kultur NR",
      rm: "Kommission für Wissenschaft, Bildung und Kultur NR",
      en: "Kommission für Wissenschaft, Bildung und Kultur NR",
    },
    KOM_12_: {
      color: "black",
      de: "Kommission für Rechtsfragen NR",
      fr: "Kommission für Rechtsfragen NR",
      it: "Kommission für Rechtsfragen NR",
      rm: "Kommission für Rechtsfragen NR",
      en: "Kommission für Rechtsfragen NR",
    },
    KOM_4_: {
      color: "black",
      de: "Aussenpolitische Kommission NR",
      fr: "Aussenpolitische Kommission NR",
      it: "Aussenpolitische Kommission NR",
      rm: "Aussenpolitische Kommission NR",
      en: "Aussenpolitische Kommission NR",
    },
    KOM_27_: {
      color: "black",
      de: "Verwaltungsdelegation",
      fr: "Verwaltungsdelegation",
      it: "Verwaltungsdelegation",
      rm: "Verwaltungsdelegation",
      en: "Verwaltungsdelegation",
    },
    KOM_708_: {
      color: "black",
      de: "Büro Vereinigte Bundesversammlung",
      fr: "Büro Vereinigte Bundesversammlung",
      it: "Büro Vereinigte Bundesversammlung",
      rm: "Büro Vereinigte Bundesversammlung",
      en: "Büro Vereinigte Bundesversammlung",
    },
    KOM_35_: {
      color: "black",
      de: "Delegation bei der parlamentarischen Versammlung der OSZE",
      fr: "Delegation bei der parlamentarischen Versammlung der OSZE",
      it: "Delegation bei der parlamentarischen Versammlung der OSZE",
      rm: "Delegation bei der parlamentarischen Versammlung der OSZE",
      en: "Delegation bei der parlamentarischen Versammlung der OSZE",
    },
    KOM_1094_: {
      color: "black",
      de: "Arbeitsgruppe Hochseeschifffahrts-Bürgschaften der Geschäftsprüfungskommissionen-V",
      fr: "Arbeitsgruppe Hochseeschifffahrts-Bürgschaften der Geschäftsprüfungskommissionen-V",
      it: "Arbeitsgruppe Hochseeschifffahrts-Bürgschaften der Geschäftsprüfungskommissionen-V",
      rm: "Arbeitsgruppe Hochseeschifffahrts-Bürgschaften der Geschäftsprüfungskommissionen-V",
      en: "Arbeitsgruppe Hochseeschifffahrts-Bürgschaften der Geschäftsprüfungskommissionen-V",
    },
    KOM_711_: {
      color: "black",
      de: "Delegation für die Beziehungen zum Italienischen Parlament",
      fr: "Delegation für die Beziehungen zum Italienischen Parlament",
      it: "Delegation für die Beziehungen zum Italienischen Parlament",
      rm: "Delegation für die Beziehungen zum Italienischen Parlament",
      en: "Delegation für die Beziehungen zum Italienischen Parlament",
    },
    KOM_30_: {
      color: "black",
      de: "Redaktionskommission",
      fr: "Redaktionskommission",
      it: "Redaktionskommission",
      rm: "Redaktionskommission",
      en: "Redaktionskommission",
    },
    KOM_1111_: {
      color: "black",
      de: "Kommission 19.078-NR",
      fr: "Kommission 19.078-NR",
      it: "Kommission 19.078-NR",
      rm: "Kommission 19.078-NR",
      en: "Kommission 19.078-NR",
    },
    KOM_29_: {
      color: "black",
      de: "Begnadigungskommission",
      fr: "Begnadigungskommission",
      it: "Begnadigungskommission",
      rm: "Begnadigungskommission",
      en: "Begnadigungskommission",
    },
    KOM_10_: {
      color: "black",
      de: "Kommission für Wirtschaft und Abgaben NR",
      fr: "Kommission für Wirtschaft und Abgaben NR",
      it: "Kommission für Wirtschaft und Abgaben NR",
      rm: "Kommission für Wirtschaft und Abgaben NR",
      en: "Kommission für Wirtschaft und Abgaben NR",
    },
    KOM_710_: {
      color: "black",
      de: "Delegation für die Beziehungen zum Französischen Parlament",
      fr: "Delegation für die Beziehungen zum Französischen Parlament",
      it: "Delegation für die Beziehungen zum Französischen Parlament",
      rm: "Delegation für die Beziehungen zum Französischen Parlament",
      en: "Delegation für die Beziehungen zum Französischen Parlament",
    },
    KOM_1114_: {
      color: "black",
      de: "Mitwirkung des Parlamentes im Bereich von Soft Law",
      fr: "Mitwirkung des Parlamentes im Bereich von Soft Law",
      it: "Mitwirkung des Parlamentes im Bereich von Soft Law",
      rm: "Mitwirkung des Parlamentes im Bereich von Soft Law",
      en: "Mitwirkung des Parlamentes im Bereich von Soft Law",
    },
    KOM_33_: {
      color: "black",
      de: "Delegation bei der Interparlamentarischen Union",
      fr: "Delegation bei der Interparlamentarischen Union",
      it: "Delegation bei der Interparlamentarischen Union",
      rm: "Delegation bei der Interparlamentarischen Union",
      en: "Delegation bei der Interparlamentarischen Union",
    },
    KOM_536_: {
      color: "black",
      de: "Gerichtskommission",
      fr: "Gerichtskommission",
      it: "Gerichtskommission",
      rm: "Gerichtskommission",
      en: "Gerichtskommission",
    },
    KOM_34_: {
      color: "black",
      de: "Delegation bei der parlamentarischen Versammlung der Frankophonie",
      fr: "Delegation bei der parlamentarischen Versammlung der Frankophonie",
      it: "Delegation bei der parlamentarischen Versammlung der Frankophonie",
      rm: "Delegation bei der parlamentarischen Versammlung der Frankophonie",
      en: "Delegation bei der parlamentarischen Versammlung der Frankophonie",
    },
    KOM_712_: {
      color: "black",
      de: "Delegation für die Beziehungen zum Landtag des Fürstentums Liechtenstein",
      fr: "Delegation für die Beziehungen zum Landtag des Fürstentums Liechtenstein",
      it: "Delegation für die Beziehungen zum Landtag des Fürstentums Liechtenstein",
      rm: "Delegation für die Beziehungen zum Landtag des Fürstentums Liechtenstein",
      en: "Delegation für die Beziehungen zum Landtag des Fürstentums Liechtenstein",
    },
    KOM_709_: {
      color: "black",
      de: "Delegation für die Beziehungen zum Österreichischen Parlament",
      fr: "Delegation für die Beziehungen zum Österreichischen Parlament",
      it: "Delegation für die Beziehungen zum Österreichischen Parlament",
      rm: "Delegation für die Beziehungen zum Österreichischen Parlament",
      en: "Delegation für die Beziehungen zum Österreichischen Parlament",
    },
    KOM_1076_: {
      color: "black",
      de: "Arbeitsgruppe Bodluv der Geschäftsprüfungskommission",
      fr: "Arbeitsgruppe Bodluv der Geschäftsprüfungskommission",
      it: "Arbeitsgruppe Bodluv der Geschäftsprüfungskommission",
      rm: "Arbeitsgruppe Bodluv der Geschäftsprüfungskommission",
      en: "Arbeitsgruppe Bodluv der Geschäftsprüfungskommission",
    },
    KOM_32_: {
      color: "black",
      de: "Delegation EFTA / Europäisches Parlament-V",
      fr: "Delegation EFTA / Europäisches Parlament-V",
      it: "Delegation EFTA / Europäisches Parlament-V",
      rm: "Delegation EFTA / Europäisches Parlament-V",
      en: "Delegation EFTA / Europäisches Parlament-V",
    },
    KOM_975_: {
      color: "black",
      de: "Arbeitsgruppe Risikomanagement Bund der Geschäftsprüfungskommissionen",
      fr: "Arbeitsgruppe Risikomanagement Bund der Geschäftsprüfungskommissionen",
      it: "Arbeitsgruppe Risikomanagement Bund der Geschäftsprüfungskommissionen",
      rm: "Arbeitsgruppe Risikomanagement Bund der Geschäftsprüfungskommissionen",
      en: "Arbeitsgruppe Risikomanagement Bund der Geschäftsprüfungskommissionen",
    },
    KOM_1068_: {
      color: "black",
      de: "Gruppe Parlaments-IT-V",
      fr: "Gruppe Parlaments-IT-V",
      it: "Gruppe Parlaments-IT-V",
      rm: "Gruppe Parlaments-IT-V",
      en: "Gruppe Parlaments-IT-V",
    },
    KOM_582_: {
      color: "black",
      de: "Delegation bei der parlamentarischen Versammlung des nordatlantischen Verteidigungsbündnisses (NATO)",
      fr: "Delegation bei der parlamentarischen Versammlung des nordatlantischen Verteidigungsbündnisses (NATO)",
      it: "Delegation bei der parlamentarischen Versammlung des nordatlantischen Verteidigungsbündnisses (NATO)",
      rm: "Delegation bei der parlamentarischen Versammlung des nordatlantischen Verteidigungsbündnisses (NATO)",
      en: "Delegation bei der parlamentarischen Versammlung des nordatlantischen Verteidigungsbündnisses (NATO)",
    },
    KOM_28_: {
      color: "black",
      de: "Finanzdelegation",
      fr: "Finanzdelegation",
      it: "Finanzdelegation",
      rm: "Finanzdelegation",
      en: "Finanzdelegation",
    },
  }